Use dcfs' flexible template to our advantage to make the parsing easier.
This commit changes the dcfs' template and fixes the "namespace" prefix
in lib/{msgs.sh,tags.sh}.

Also start writing lib/tags.sh

diff --git a/test/extractmsg b/test/extractmsg
--- a/test/extractmsg
+++ b/test/extractmsg
@@ -1,18 +1,32 @@
 #!/bin/sh
 . lib/msg.sh
 
+andmap() {
+	while read -r l; do
+		eval [ ! "${l}" ] || return 1
+	done <<EOF
+"${author}" = "${eauthor}"
+"${content}" = "${econtent}"
+"${em}" = "${eem}"
+"${attach}" = "${eattach}"
+EOF
+	return 0
+}
+
 test() {
 	exit=0
 	while read -r l; do
 		eval "${l}"
-		reply="$(msg:extractmsg "${input}")"
-		[ "${reply}" != "${expected}" ] && {
-			echo ${0##*/}: expected "${expected}", got "${reply}"
+		eval "$(msg_extractmsg "${l}")"
+		andmap || {
+			echo ${0##*/}: ${l} failed
 			exit=1
 		}
 	done <<EOF
-input='viz,somethingsomething,[],[]' expected='viz somethingsomething [] []'
-input='hahaxd,"something else",[],[]' expected='hahaxd "something else" [] []'
+input="author='viz',content='somethingsomething',em='[]',attach='[]'" \
+	eauthor="viz" econtent="somethingsomething" eem=[] eattach=[]
+input="author='hahaxd',content='something else',em='[]',attach='[]'" \
+	eauthor="hahaxd" econtent="something else" eem="[]" eattach=[]
 EOF
 	return ${exit}
 }
